dev: false
lang:
  core:
    invalidPermissions: '&cYou are lacking the required permissions to execute this command.'
    invalidPlayer: '&cSorry! That player is currently offline.'
    reloadConfigurations: '&aSuccessfully reloaded all configurations.'
  commands:
    giveitem:
      usage: '&cUsage: /giveitem <player> <id> <amount>.'
      invalidItem: '&cSorry! That''s not a valid item id.'
      gaveItem: '&aYou have given &f{receiver}&r &aa &r{itemName}&a.'