dev: false
lang:
  core:
    invalidPermissions: '&cYou are lacking the required permissions to execute this command.'
    invalidPlayer: '&cSorry! That player is currently offline.'
  commands:
    giveitem:
      usage: '&cUsage: /giveitem <player> <id> <amount>.'