dev: false
db:
  type: 'SQLite'
  name: ''
  username: ''
  password: ''
  host: ''
  port: 3000
  # If using SQLite.
  file: 'foraging.db'
lang:
  core:
    invalidPermissions: '&cYou are lacking the required permissions to execute this command.'
    invalidPlayer: '&cSorry! That player is currently offline.'
  commands:
    giveitem:
      usage: '&cUsage: /giveitem <player> <id> <amount>.'
      invalidItem: '&cSorry! That''s not a valid item id.'
      gaveItem: '&aYou have given &f{receiver}&r &aa &r{itemName}&a.'
    reloadconfigurations:
      success: '&aSuccessfully reloaded all configurations.'
    summonmonster:
      usage: '&cUsage: /summonmonster <monster>.'
      invalidMonster: '&cSorry! That''s not a valid monster id.'
      success: '&aSuccessfully summoned &f{aggression_color}{monster}&r &aat your location.'
  player:
    join: '&f{player}&r &ehas joined the game.'
    quit: '&f{player}&r &ehas left the game.'
