name: Foraging
main: me.tech.foraging.Foraging
version: 1.0.0
author: Tech
depend: [HolographicDisplays, WorldGuard, WorldGuardEvents]
commands:
  cool:
    usage: cool
  giveitem:
    usage: giveitem
  reloadconfigs:
    usage: reloadconfigs
    aliases: ['reloadconfig']